model:
  embedding_dim: 256  # Even smaller for testing
  num_heads: 2
  num_layers: 2
  mlp_hidden_dim: 1024  # 4x embedding dim
  tree_embedding_dim: 256
  max_sequence_length: 1024

training:
  batch_size: 1
  learning_rate: 1e-4
  warmup_steps: 100
  grad_clip: 1.0
  optimizer:
    name: "adamw"  # Options: adamw, adam, sgd, adafactor
    memory_efficient: true
  mixed_precision: true  # Enable automatic mixed precision
  gradient_checkpointing: true  # Enable gradient checkpointing 